---
grails:
    profile: web
    codegen:
        defaultPackage: restaurantetocomfome
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
environments:
    development:
        management:
            endpoints:
                enabled-by-default: true
                web:
                    base-path: '/actuator'
                    exposure:
                        include: '*'
    production:
        management:
            endpoints:
                enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
                - text/html
                - application/xhtml+xml
            js: text/javascript
            json:
                - application/json
                - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
                - application/hal+json
                - application/hal+xml
            xml:
                - text/xml
                - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none
#---
#grails:
#    plugin:
#        springsecurity:
#            rest:
#                token:
#                    storage:
#                        jwt:
#                            secret: '9e548c06c9bc1fae358e0bb166097c47cafc9e8be05bca289409ec77e0836964'
#                            expiration: 7200
#            userLookup:
#                userDomainClassName: comum.Usuario
#                authorityJoinClassName: comum.UsuarioPermissao
#            authority:
#                className: comum.Permisao
#            securityConfigType:  Requestmap
#            useSecurityEventListener: true
#            requestMap:
#                className: comum.RequestMap
#            filterChain:
#                chainMap:
#                    -
#                        pattern: /assets/**
#                        filters: none
#                    -
#                        pattern: /**/js/**
#                        filters: none
#                    -
#                        pattern: /**/css/**
#                        filters: none
#                    -
#                        pattern: /**/images/**
#                        filters: none
#                    - # Stateless chain
#                        pattern: /api/**
#                        filters: JOINED_FILTERS,-anonymousAuthenticationFilter,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter
#                    - # Traditional Chain
#                        pattern: /**
#                        filters: JOINED_FILTERS,-restTokenValidationFilter,-restExceptionTranslationFilter
#                controllerAnnotations:
#                    staticRules:
#                        -
#                            pattern: /
#                            access:
#                                - permitAll
#                        -
#                            pattern: /error
#                            access:
#                                - permitAll
#                        -
#                            pattern: /index
#                            access:
#                                - permitAll
#                        -
#                            pattern: /index.gsp
#                            access:
#                                - permitAll
#                        -
#                            pattern: /shutdown
#                            access:
#                                - permitAll
#                        -
#                            pattern: /assets/**
#                            access:
#                                - permitAll
#                        -
#                            pattern: /**/js/**
#                            access:
#                                - permitAll
#                        -
#                            pattern: /**/css/**
#                            access:
#                                - permitAll
#                        -
#                            pattern: /**/images/**
#                            access:
#                                - permitAll
#                        -
#                            pattern: /**/favicon.ico/**
#                            access:
#                                - permitAll

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:

environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost/restaurante
    test:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost/restaurante
    production:
        dataSource:
            dbCreate: none
            url: jdbc:mysql://localhost/restaurante
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED